// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: 'AIzaSyCDBnm_t_8MXmlH8F6Sj84uZ4hf7mQsDtk',
    apiKey: 'AIzaSyAY7mJ1KP6tD3Tl5TUOwUmCqRzYBfy_MPA',
    appId: '1:902814305409:web:f2012b25292e0a52a7d180',
    messagingSenderId: '902814305409',
    projectId: 'cloudkitchen-b3d92',
    authDomain: 'cloudkitchen-b3d92.firebaseapp.com',
    storageBucket: 'cloudkitchen-b3d92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMYBUiXs2jFnAEFcg3QyUVUIZ-6ccH2o4',
    appId: '1:902814305409:android:2c65f7d3bb97bc90a7d180',
    messagingSenderId: '902814305409',
    projectId: 'cloudkitchen-b3d92',
    storageBucket: 'cloudkitchen-b3d92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY7mJ1KP6tD3Tl5TUOwUmCqRzYBfy_MPA',
    appId: '1:902814305409:ios:e57f5fad39b83864a7d180',
    messagingSenderId: '902814305409',
    projectId: 'cloudkitchen-b3d92',
    storageBucket: 'cloudkitchen-b3d92.firebasestorage.app',
    iosBundleId: 'com.example.cloudKitchen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY7mJ1KP6tD3Tl5TUOwUmCqRzYBfy_MPA',
    appId: '1:902814305409:ios:e57f5fad39b83864a7d180',
    messagingSenderId: '902814305409',
    projectId: 'cloudkitchen-b3d92',
    storageBucket: 'cloudkitchen-b3d92.firebasestorage.app',
    iosBundleId: 'com.example.cloudKitchen2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDBnm_t_8MXmlH8F6Sj84uZ4hf7mQsDtk',
    appId: '1:902814305409:web:bfb6e8b015c5bf18a7d180',
    messagingSenderId: '902814305409',
    projectId: 'cloudkitchen-b3d92',
    authDomain: 'cloudkitchen-b3d92.firebaseapp.com',
    storageBucket: 'cloudkitchen-b3d92.firebasestorage.app',
  );
}
